### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by zer0gra** [Fer3on07/Farlight84-Simple-EAC-Bypass#1]
The esaiest way to bypass EAC on Farlight 84.
                                             Comes to you by Unknowncheats!
Unable to locate Farlight 84 root directory, please enter the path manually.
>

what do i do here

**Comment by Fer3on07** [comment]
This is the default location for steam farlight84
`C:\Program Files (x86)\Steam\steamapps\common\Farlight 84`

If you installed it on local driver D or E or F so you should write it manually to the console.
